# Generated by Django 5.2.9 on 2026-01-02 18:17

import badges.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0002_remove_badgeprofile_linkedin_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgeprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=badges.storage_backends.MediaStorage(),
                upload_to="profile_images/",
            ),
        ),
    ]
